logging:
  level:
    org.hibernate.SQL: trace
    root: WARN
    dev:
      riac:
        trapcount:
          report:
            trapcountreport: trace
    org.hibernate.type.descriptor.sql: trace

spring:
  datasource:
    url: jdbc:sqlserver://gsl-data-dev.database.windows.net;database=TrapCounts
    username: RicardoZ_Dev
    password: "#v9g@h4rmNY8qNM$"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

trapcount:
  skip:
    send:
      email: false